import 'package:build_test/build_test.dart';
import 'package:merging_builder/merging_builder.dart';
import 'package:test/test.dart';

import 'src/generators/assistant_generator.dart';
import 'src/mock_builders/mock_standalone_builder.dart';

/// Tests if the builder generates the expected output file.
///
/// To run this program navigate to the top directory the package
/// [merging_builder] and use the command:
///
/// # pub run build_runner test -- -r expanded
void main() {
  test('Test: standalone_builder. \n Generate standalone files.', () async {
    /// Defining source assets.
    final Map<String, String> sourceAssets = {
      '$_pkgName|lib/input/researcher_a.dart': _researcher_aDotDart,
      '$_pkgName|lib/input/researcher_b.dart': _researcher_bDotDart,
    };

    final Map<String, String> outputs = {
      '$_pkgName|lib/output/assistant_researcher_a.dart':
          _assistant_researcher_aDotDart,
      '$_pkgName|lib/output/assistant_researcher_b.dart':
          _assistant_researcher_bDotDart,
    };

    /// Builder instance.
    final builder = MockStandaloneBuilder(
      generator: AssistantGenerator(),
      inputFiles: 'lib/input/*.dart',
      outputFiles: 'lib/output/assistant_(*).dart',

    );
    await testBuilder(
      builder,
      sourceAssets,
      outputs: outputs,
      rootPackage: _pkgName,
      reader: await PackageAssetReader.currentIsolate(),
    );
  });
}

const String _pkgName = 'merging_builder';

const _assistant_researcher_aDotDart = r'''
// GENERATED CODE. DO NOT MODIFY. Generated by AssistantGenerator.

final String assistants = 'Thomas, Mayor';
''';

const _assistant_researcher_bDotDart = r'''
// GENERATED CODE. DO NOT MODIFY. Generated by AssistantGenerator.

final String assistants = 'Philip, Martens';
''';

const _researcher_aDotDart = r'''
import 'package:merging_builder/src/annotations/add_integers.dart';
import 'package:merging_builder/src/annotations/add_names.dart';
import 'package:merging_builder/src/annotations/add_numbers.dart';

/// Const class for testing purposes.
@AddNames()
@AddNumbers()
@AddIntegers()
class ResearcherA {
  const ResearcherA();

  final List<String> names = const ['Thomas', 'Mayor'];

  final List<int> integers = const [47, 91];

  final num number = 19;

  final String title = 'ResearcherA';
}
''';

const _researcher_bDotDart = r'''
import 'package:merging_builder/src/annotations/add_integers.dart';
import 'package:merging_builder/src/annotations/add_names.dart';
import 'package:merging_builder/src/annotations/add_numbers.dart';

/// Const class for testing purposes.
@AddNumbers()
@AddIntegers()
@AddNames()
class ResearcherB {
  const ResearcherB();

  final List<String> names = const ['Philip', 'Martens'];

  final Set<int> integers = const {7, 9};

  final num number = 119;

  final String title = 'ResearcherB';
}
''';
