import 'dart:async';

import 'package:build/build.dart';
import 'package:exception_templates/exception_templates.dart';
import 'package:file/file.dart' show Directory, File;
import 'package:glob/glob.dart';
import 'package:glob/list_local_fs.dart' show ListLocalFileSystem;
import 'package:merging_builder/src/enum/build_location.dart';
import 'package:path/path.dart' as path;
import 'package:source_gen/source_gen.dart' show Generator, LibraryReader;

import 'synthetic_builder.dart';

/// Builder that uses synthetic input and
/// creates one output file for each input file.
class StandaloneBuilder({
  /// Instance of [Generator],
  required final Generator generator,

  super.inputFiles = 'lib/*.dart',

  /// Path to output files.
  /// The symbol `(*)` will be replaced with the corresponding input file name
  /// (omitting the extension).
  ///
  /// Example: `lib/standalone_(*).dart`
  final String outputFiles = 'lib/standalone_(*).dart',

  super.buildLocation = BuildLocation.lib,
  super.header,
  super.footer,
  super.formatter,

  /// The root directory of the package the build is applied to.
  /// This variable does not need to be set if the build command is initiated
  /// from the root directory of the package.
  String root = '',
}) extends SyntheticBuilder {
  /// Lazily computes the output file names by replacing the
  /// placeholder `(*)` in [outputFiles] with the input file basename.
  late final List<String> _resolvedOutputFiles = _outputPaths();

  /// The root directory of the package the build is applied to.
  /// This variable does not need to be set if the build command is initiated
  /// from the root directory of the package.
  final String root = root.trim();

  /// Returns a map of type `Map<String, List<String>>`
  /// with content {synthetic input: list of output files}.
  @override
  Map<String, List<String>> get buildExtensions => {
    buildLocation.value: _resolvedOutputFiles,
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final libAssetIds = await libraryAssetIds(buildStep);
    // Accessing libraries.
    for (final libAssetId in libAssetIds) {
      final library = LibraryReader(
        await buildStep.resolver.libraryFor(libAssetId),
      );
      // Calling generator.generate.
      log.fine('Running ${generator.runtimeType} on: ${libAssetId.path}.');

      // Create output file name.
      await buildStep.writeAsString(
        AssetId(buildStep.inputId.package, _outputFile(libAssetId)),
        arrangeContent(
          (await generator.generate(library, buildStep)) ?? '',
          generatedBy: 'Generated by ${generator.runtimeType}. ',
        ),
      );
    }
  }

  /// Returns the path of the output file for a given input file [assetId].
  String _outputFile(AssetId assetId) {
    final basename = path.basenameWithoutExtension(assetId.path);
    return outputFiles.replaceAll(RegExp(r'\(\*\)'), basename);
  }

  /// Returns a list of output file paths.
  List<String> _outputPaths() {
    final result = <String>[];
    final files = <File>[];
    buildLocation.validatePath(inputFiles);
    buildLocation.validatePath(outputFiles);
    final glob = Glob(inputFiles);

    // Collect all files
    for (final entity in glob.listSync(root: root)) {
      if (entity is Directory) {
        for (final e in entity.listSync()) {
          if (e is File) {
            files.add(e);
          }
        }
      } else if (entity is File) {
        files.add(entity);
      }
    }

    // Validate files
    for (final inputFile in files) {
      final basename = path.basenameWithoutExtension(inputFile.path);
      final outputFileName = outputFiles.replaceAll(
        RegExp(r'\(\*\)'),
        basename,
      );
      // Check if output clashes with input files.
      if (path.equals(outputFileName, inputFile.path)) {
        throw ErrorOf<StandaloneBuilder>(
          message: 'Output file clashes with input file!',
          expectedState:
              'Output files must not overwrite input files. '
              'Check the [StandaloneBuilder] '
              'constructor argument [outputFiles].',
          invalidState: 'Output: $outputFileName is also an input file.',
        );
      }
      result.add(outputFileName);
    }
    return result;
  }
}
