// Contains file content as String constants.
// Example: researchers.dart => researchers_dot_dart.

const String pkgName = 'researcher';

// Defining source assets.
final Map<String, String> sourceAssets = {
  '$pkgName|lib/source_assets/researcher_a.dart': researcher_a_dot_dart,
  '$pkgName|lib/source_assets/researcher_b.dart': researcher_b_dot_dart,
};

const researchers_dot_dart = r'''
// GENERATED CODE. DO NOT MODIFY. Generated by AddNamesGenerator.

/// Added names.
final name0 = ['Thomas', 'Mayor'];
final name1 = ['Philip', 'Martens'];

final List<List<String>> names = [
  ['Thomas', 'Mayor'],
  ['Philip', 'Martens'],
];

/// This is the footer.
''';

const assistant_researcher_a_dot_dart = r'''
// GENERATED CODE. DO NOT MODIFY. Generated by AssistantGenerator.

final String assistants = 'Thomas, Mayor';
''';

const assistant_researcher_b_dot_dart = r'''
// GENERATED CODE. DO NOT MODIFY. Generated by AssistantGenerator.

final String assistants = 'Philip, Martens';
''';

const researcher_a_dot_dart = r'''
library researcher_a;

import 'package:researcher/researcher.dart';

/// Const class for testing purposes.
@AddNames()
@AddNumbers()
@AddIntegers()
class ResearcherA {
  const ResearcherA();

  final List<String> names = const ['Thomas', 'Mayor'];

  final List<int> integers = const [47, 91];

  final num number = 19;

  final String title = 'ResearcherA';
}
''';

const researcher_b_dot_dart = r'''
library researcher_b;

import 'package:researcher/researcher.dart';

/// Const class for testing purposes.
@AddNumbers()
@AddIntegers()
@AddNames()
class ResearcherB {
  const ResearcherB();

  final List<String> names = const ['Philip', 'Martens'];

  final Set<int> integers = const {7, 9};

  final num number = 119;

  final String title = 'ResearcherB';
}
''';

const add_integers_dot_dart = r'''
/// Annotation for testing purposes.
class AddIntegers {
  const AddIntegers();
}
''';

const add_names_dot_dart = r'''
/// Annotation for testing purposes.
class AddNames {
  const AddNames();
}
''';

const add_numbers_dot_dart = r'''
/// Annotation for testing purposes.
class AddNumbers {
  const AddNumbers();
}
''';
