// GENERATED CODE. DO NOT MODIFY. Generated by AddNamesGenerator.

/// Added names.
final name0 = ['Thomas', 'Mayor'];
final name1 = ['Philip', 'Martens'];

final List<List<String>> names = [
  ['Thomas', 'Mayor'],
  ['Philip', 'Martens'],
];

/// This is the footer.
