// GENERATED CODE. DO NOT MODIFY. Generated by AddNamesGenerator.

// Header specified in build.yaml.
final name0 = ['Thomas', 'Mayor'];
final name1 = ['Philip', 'Martens'];

final List<List<String>> names = [
  ['Thomas', 'Mayor'],
  ['Philip', 'Martens'],
];

// Footer specified in build.yaml.
