// GENERATED CODE. DO NOT MODIFY. Generated by AddNamesGenerator. 2020-06-01 22:02:49.146751.

/// Added names. (Specified as header.)
final name0 = ['Thomas', 'Mayor'];
final name1 = ['Philip', 'Martens'];

final List<List<String>> names = [
  ['Thomas', 'Mayor'],
  ['Philip', 'Martens'],
];

/// This is the footer.
